version: '3'

services:
  app:
    build: ./project
    restart: always
    depends_on:
      - app-db
    environment:
      PG_HOST: "app-db"
      PG_PORT: "5432"
      PG_USER: "admin"
      PG_PASSWORD: "admin1234"
      PG_DATABASE: "app"
    ports:
      - 3000:3000
    networks:
      - app_network

  app-db:
    image: postgres:10-alpine3.13
    restart: always
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "app"
    ports:
      - 3001:5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge